Repository GothicVRProject/GothicVR, pull requests merged in 2023-10, with the labels that each got.

#206 Feature/music tick
  Assets/GothicVR/Dependencies/PxCs.dll
  Assets/GothicVR/Resources/Prefabs/Vobs/oCZoneMusic.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/oCZoneMusic.prefab.meta
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSound.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSound.prefab.meta
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSoundDaytime.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSoundDaytime.prefab.meta
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scenes/General.unity
  Assets/GothicVR/Scripts/Bootstrap/PhoenixBootstrapper.cs
  Assets/GothicVR/Scripts/Caches/AssetCache.cs
  Assets/GothicVR/Scripts/Caches/PrefabCache.cs
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/SoundCreator.cs
  Assets/GothicVR/Scripts/Creator/SoundCreator.cs.meta
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Creator/WaynetCreator.cs
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Manager/AudioManager.cs
  Assets/GothicVR/Scripts/Manager/AudioManager.cs.meta
  Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
  Assets/GothicVR/Scripts/Manager/Culling.meta
  Assets/GothicVR/Scripts/Manager/Culling/VobMeshCullingManager.cs
  Assets/GothicVR/Scripts/Manager/Culling/VobMeshCullingManager.cs.meta
  Assets/GothicVR/Scripts/Manager/Culling/VobSoundCullingManager.cs
  Assets/GothicVR/Scripts/Manager/Culling/VobSoundCullingManager.cs.meta
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
  Assets/GothicVR/Scripts/Manager/MusicManager.cs
  Assets/GothicVR/Scripts/Manager/MusicManager.cs.meta
  Assets/GothicVR/Scripts/Phoenix/Interface/Vm/VmGothicExternals.cs
  Assets/GothicVR/Scripts/Phoenix/Util/MusicColliderHandler.cs
  Assets/GothicVR/Scripts/Player/Climb/RayTeleportClimb.cs
  Assets/GothicVR/Scripts/Vob/ItemGrabInteractable.cs
  Assets/GothicVR/Scripts/Vob/SoundDaytime.cs
  Assets/GothicVR/Scripts/Vob/SoundDaytimeHandler.cs
  Assets/GothicVR/Scripts/Vob/SoundDaytimeHandler.cs.meta
  Assets/GothicVR/Scripts/Vob/SoundHandler.cs
  Assets/GothicVR/Scripts/Vob/SoundHandler.cs.meta
  Assets/GothicVR/Scripts/Vob/VobMusicProperties.cs
  Assets/GothicVR/Scripts/Vob/VobMusicProperties.cs.meta
  Assets/GothicVR/Scripts/Vob/VobSoundDaytimeProperties.cs
  Assets/GothicVR/Scripts/Vob/VobSoundDaytimeProperties.cs.meta
  Assets/GothicVR/Scripts/Vob/VobSoundProperties.cs
  Assets/GothicVR/Scripts/Vob/VobSoundProperties.cs.meta
Labels: quick

#220 Bugfix/missing chest meshes and optimized vob warnings
  Assets/GothicVR/Scripts/Creator/DebugAnimationCreator.cs
  Assets/GothicVR/Scripts/Creator/DebugAnimationCreatorVelaya.cs
  Assets/GothicVR/Scripts/Creator/Meshes/AbstractMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/WorldMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Demo/DemoContainerLoot.cs
Labels: quick

#223 Feature/separate world meshes
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Creator/Meshes/AbstractMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/WorldMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Creator/WorldCreator.cs
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Manager/Culling/WorldCullingManager.cs
  Assets/GothicVR/Scripts/Manager/Culling/WorldCullingManager.cs.meta
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
  Assets/GothicVR/Scripts/Phoenix/Data/WorldData.cs
Labels: quick

#232 Sounds fixed - Right ones will be enabled next to player when spawned.
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Caches/LookupCache.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
Labels: bug

#234 Re-added collission for Vobs.
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
Labels: quick

#247 Some bugfixes to prepare for release
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/MainMenu.prefab
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
  Assets/GothicVR/Scripts/Player/Climb/RayTeleportClimb.cs
  Assets/GothicVR/Scripts/Player/Menu/MenuManager.cs
Labels: bug

#250 Upgrade to Unity 2022.3.12f1
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Settings/URP-Performant-Renderer.asset
  Assets/TextMesh Pro/Resources/TMP Settings.asset
  Assets/TextMesh Pro/Shaders/TMP_Bitmap-Custom-Atlas.shader
  Assets/TextMesh Pro/Shaders/TMP_Bitmap-Mobile.shader
  Assets/TextMesh Pro/Shaders/TMP_Bitmap.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF Overlay.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF SSD.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF-Mobile Masking.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF-Mobile Overlay.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF-Mobile-2-Pass.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF-Mobile.shader
  Assets/TextMesh Pro/Shaders/TMP_SDF.shader
  Assets/TextMesh Pro/Shaders/TMP_Sprite.shader
  Assets/XR/Settings/OpenXR Package Settings.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/ShaderGraphSettings.asset
Labels: enhancement
