Repository GothicVRProject/GothicVR, pull requests merged in 2023-08, with the labels that each got.

#171 Bugfix/climbable ladders
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/VRPlayer.prefab
  Assets/GothicVR/Scripts/Creator/Meshes/AbstractMeshCreator.cs
Labels: bug

#173 Bugfix/music world loading
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Bootstrap/PhoenixBootstrapper.cs
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
Labels: bug

#175 Feature/ladder teleport
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/VRPlayer.prefab
  Assets/GothicVR/Scenes/General.unity
  Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
  Assets/GothicVR/Scripts/Player/Climb/RayTeleportClimb.cs
  Assets/GothicVR/Scripts/Player/Climb/RayTeleportClimb.cs.meta
Labels: enhancement, vr-feature, Pipeline

#181 bugfix/ladder teleport indicator
  Assets/GothicVR/Resources/Materials/ArrowMaterial.mat
Labels: bug

#183 add menu skip flag
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
Labels: quick

#200 Separated Vobs into Teleport and NonTeleport entries.
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Creator/WorldCreator.cs
Labels: bug, quick
