Repository GothicVRProject/GothicVR, pull requests merged in 2023-11, with the labels that each got.

#233 Feature/npc on the ground
  Assets/GothicVR/Resources/Prefabs/NPC.prefab
  Assets/GothicVR/Scripts/Creator/NpcCreator.cs
  Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
  Assets/GothicVR/Scripts/Manager/NpcHelper.cs
  Assets/GothicVR/Scripts/Manager/WayNetHelper.cs
  Assets/GothicVR/Scripts/Npc/Actions/AnimationActions/AbstractWalkAnimationAction.cs
  Assets/GothicVR/Scripts/Phoenix/Interface/Vm/VmGothicExternals.cs
Labels: quick

#251 Feature/vob particlefx
  Assets/GothicVR/Resources/Prefabs/Vobs/vobPfx.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/vobPfx.prefab.meta
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Bootstrap/PhoenixBootstrapper.cs
  Assets/GothicVR/Scripts/Caches/AssetCache.cs
  Assets/GothicVR/Scripts/Caches/PrefabCache.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Extensions/MaterialExtension.cs
  Assets/GothicVR/Scripts/Manager/GameData.cs
  Assets/GothicVR/Scripts/Vob/VobPfxProperties.cs
  Assets/GothicVR/Scripts/Vob/VobPfxProperties.cs.meta
  ProjectSettings/GraphicsSettings.asset
Labels: quick

#261 Feature/sound volume sliders
  Assets/GothicVR/Resources/AudioMixer.mixer
  Assets/GothicVR/Resources/AudioMixer.mixer.meta
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/MainMenu.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSound.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSoundDaytime.prefab
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scenes/General.unity
  Assets/GothicVR/Scripts/Manager/ConstantsManager.cs
  Assets/GothicVR/Scripts/Manager/MusicManager.cs
  Assets/GothicVR/Scripts/Player/Menu/MenuManager.cs
  Assets/GothicVR/Scripts/UI/AudioMixerHandler.cs
  Assets/GothicVR/Scripts/UI/AudioMixerHandler.cs.meta
Labels: enhancement

#266 Use given samplerate and channel number for Sounds
  Assets/GothicVR/Dependencies/PxCs.dll
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Manager/VobHelper.cs
  Assets/GothicVR/Scripts/Phoenix/Util/SoundConverter.cs
  Assets/GothicVR/Scripts/Vob/SoundDaytimeHandler.cs
Labels: bug

#268 Routine waypoint based pathfinding POC
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Creator/WaynetCreator.cs
  Assets/GothicVR/Scripts/Creator/WorldCreator.cs
  Assets/GothicVR/Scripts/Debugging/DijkstraPathRendererDebug.cs
  Assets/GothicVR/Scripts/Debugging/DijkstraPathRendererDebug.cs.meta
  Assets/GothicVR/Scripts/Extensions/GameObjectExtension.cs
  Assets/GothicVR/Scripts/Manager/GameData.cs
  Assets/GothicVR/Scripts/Manager/WayNetHelper.cs
  Assets/GothicVR/Scripts/World/DijkstraWaypoint.cs
  Assets/GothicVR/Scripts/World/DijkstraWaypoint.cs.meta
Labels: help wanted
