Repository GothicVRProject/GothicVR, pull requests merged in 2024-03, with the labels that each got.

#314 Bugfix/music change
  Assets/GothicVR-Lab/Scenes/Lab.unity
  Assets/GothicVR-Lab/Scripts/Handler/LabMusicHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/LabMusicHandler.cs.meta
  Assets/GothicVR-Lab/Scripts/LabBootstrapper.cs
  Assets/GothicVR/Resources/Prefabs/Vobs/oCZoneMusic.prefab
  Assets/GothicVR/Scripts/Manager/MusicManager.cs
Labels: quick

#311 Feature/OcMobProperImplementation
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
Labels: enhancement, quick

#322 Fix Texture cache cleaning
  Assets/GothicVR/Scripts/Caches/TextureCache.cs
Labels: bug

#320 bug fix - no physics on released items
  Assets/GothicVR/Scripts/Manager/Culling/VobMeshCullingManager.cs
  Assets/GothicVR/Scripts/Vob/ItemGrabInteractable.cs
Labels: bug

#326 add Conroller Support for devices
  Assets/XR/Settings/OpenXR Package Settings.asset
Labels: bug, quick

#319 316 optimize ci cache lfs data
  .github/workflows/test_and_build.yml
Labels: Pipeline

#329 Add initial implementation of zCVobAnimate
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobAnimate.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobAnimate.prefab.meta
  Assets/GothicVR/Scripts/Caches/AssetCache.cs
  Assets/GothicVR/Scripts/Caches/MorphMeshCache.cs
  Assets/GothicVR/Scripts/Caches/PrefabCache.cs
  Assets/GothicVR/Scripts/Creator/Meshes/V2/Builder/AbstractMeshBuilder.cs
  Assets/GothicVR/Scripts/Creator/Meshes/V2/Builder/NpcHeadMeshBuilder.cs
  Assets/GothicVR/Scripts/Creator/Meshes/V2/Builder/VobMeshBuilder.cs
  Assets/GothicVR/Scripts/Creator/Meshes/V2/MeshFactory.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Misc.meta
  Assets/GothicVR/Scripts/Misc/AbstractMorphAnimation.cs
  Assets/GothicVR/Scripts/Misc/AbstractMorphAnimation.cs.meta
  Assets/GothicVR/Scripts/Npc/HeadMorph.cs
  Assets/GothicVR/Scripts/Vob/VobAnimateMorph.cs
  Assets/GothicVR/Scripts/Vob/VobAnimateMorph.cs.meta
Labels: enhancement
