Repository GothicVRProject/GothicVR, pull requests merged in 2024-01, with the labels that each got.

#287 Bugfix/Font-wrap-wrong
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/MainMenu.prefab
  Assets/GothicVR/Scripts/UI/FontManager.cs
Labels: bug

#289 Feature/sky revamped
  Assets/GothicVR/Editor/Scripts/Tools/FeatureFlagTool.cs
  Assets/GothicVR/Resources/Materials/GothicSky.mat
  Assets/GothicVR/Resources/worldLightingSettings.lighting
  Assets/GothicVR/Resources/worldLightingSettings.lighting.meta
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scenes/Worlds/world.zen.unity
  Assets/GothicVR/Scripts/Creator/WorldCreator.cs
  Assets/GothicVR/Scripts/Data/SkyLayerData.cs
  Assets/GothicVR/Scripts/Data/SkyLayerData.cs.meta
  Assets/GothicVR/Scripts/Data/SkyState.cs
  Assets/GothicVR/Scripts/Data/SkyState.cs.meta
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Extensions/NumericsExtension.cs
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
  Assets/GothicVR/Scripts/Manager/SkyManager.cs
  Assets/GothicVR/Scripts/Manager/SkyManager.cs.meta
  Assets/GothicVR/Scripts/UI/TextureManager.cs
  Assets/GothicVR/Scripts/World/GameTime.cs
  Assets/GothicVR/Shaders/Skybox.shader
  Assets/GothicVR/Shaders/Skybox.shader.meta
Labels: enhancement

#292 Bugfix/sound-crackling
  Assets/GothicVR/Scripts/Creator/Sounds/SoundCreator.cs
Labels: bug

#291 Feature/barrier
  Assets/GothicVR-Lab/Scripts/Handler/LockableHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/NpcHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/VobHandAttachPointsHandler.cs
  Assets/GothicVR/Editor/Scripts/Tools/FeatureFlagTool.cs
  Assets/GothicVR/Scenes/Bootstrap.unity
  Assets/GothicVR/Scripts/Caches/AssetCache.cs
  Assets/GothicVR/Scripts/Creator/MeshCreatorFacade.cs
  Assets/GothicVR/Scripts/Creator/MeshCreatorFacade.cs.meta
  Assets/GothicVR/Scripts/Creator/Meshes/AbstractMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/MeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/MeshCreator.cs.meta
  Assets/GothicVR/Scripts/Creator/Meshes/NpcMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/PolyStripMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/Meshes/PolyStripMeshCreator.cs.meta
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
  Assets/GothicVR/Scripts/Creator/NpcCreator.cs
  Assets/GothicVR/Scripts/Creator/VobCreator.cs
  Assets/GothicVR/Scripts/Creator/WaynetCreator.cs
  Assets/GothicVR/Scripts/Creator/WorldCreator.cs
  Assets/GothicVR/Scripts/Debugging/FeatureFlags.cs
  Assets/GothicVR/Scripts/Demo/DemoContainerLoot.cs
  Assets/GothicVR/Scripts/Globals/Constants.cs
  Assets/GothicVR/Scripts/Manager/BarrierManager.cs
  Assets/GothicVR/Scripts/Manager/BarrierManager.cs.meta
  Assets/GothicVR/Scripts/Manager/GvrSceneManager.cs
  Assets/GothicVR/Scripts/Manager/SkyManager.cs
  Assets/GothicVR/Scripts/UI/FontManager.cs
  Assets/GothicVR/Scripts/UI/TextureManager.cs
  Assets/GothicVR/Shaders/Barrier.shader
  Assets/GothicVR/Shaders/Barrier.shader.meta
  Assets/GothicVR/Shaders/ThunderShader.shader
  Assets/GothicVR/Shaders/ThunderShader.shader.meta
Labels: enhancement

#293 Bugfix/fix adpcm decoding
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/VRPlayer.prefab
  Assets/GothicVR/Scripts/Creator/Sounds/SoundCreator.cs
Labels: bug

#294 Feature/sky improvements
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/VRPlayer.prefab
  Assets/GothicVR/Scripts/Data/SkyState.cs
  Assets/GothicVR/Scripts/Data/SkyStateRain.cs
  Assets/GothicVR/Scripts/Data/SkyStateRain.cs.meta
  Assets/GothicVR/Scripts/Extensions/NumericsExtension.cs
  Assets/GothicVR/Scripts/Manager/Settings/GameSettings.cs
  Assets/GothicVR/Scripts/Manager/Settings/SettingsManager.cs
  Assets/GothicVR/Scripts/Manager/SkyManager.cs
  Assets/GothicVR/Scripts/Manager/XRDeviceSimulatorManager.cs
  Assets/GothicVR/Scripts/Npc/HeadMorph.cs
  Assets/GothicVR/Scripts/World/GameTime.cs
  Assets/GothicVR/Shaders/Barrier.shader
  Assets/GothicVR/Shaders/Skybox.shader
  ProjectSettings/GraphicsSettings.asset
Labels: enhancement

#299 Bugfix/lab issues
  Assets/GothicVR-Lab/Scenes/Lab.unity
  Assets/GothicVR-Lab/Scripts/Handler/ILabHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/ILabHandler.cs.meta
  Assets/GothicVR-Lab/Scripts/Handler/LabLockableLabHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/LabLockableLabHandler.cs.meta
  Assets/GothicVR-Lab/Scripts/Handler/LabNpcLabHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/LabNpcLabHandler.cs.meta
  Assets/GothicVR-Lab/Scripts/Handler/LabVobHandAttachPointsLabHandler.cs
  Assets/GothicVR-Lab/Scripts/Handler/LabVobHandAttachPointsLabHandler.cs.meta
  Assets/GothicVR-Lab/Scripts/LabBootstrapper.cs
  Assets/GothicVR/Scripts/Globals/GvrEvents.cs
  Assets/GothicVR/Scripts/Manager/GvrBootstrapper.cs
  Assets/GothicVR/Scripts/Player/BasicMovement/ControllerManager.cs
Labels: quick

#303 Bugfix/fix teleport ray collider
  Assets/GothicVR/Resources/Prefabs/UI Element Prefabs/VRPlayer.prefab
  Assets/GothicVR/Resources/Prefabs/Vobs/zCVobSpot.prefab
  Assets/GothicVR/Resources/Prefabs/WayPoint.prefab
  Assets/GothicVR/Scripts/Creator/Meshes/VobMeshCreator.cs
Labels: bug
